name: Build Preview for Pull Requests

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build

      - name: Upload build output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-dist
          path: ./dist